# Generated by Django 6.0.3 on 2026-04-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('livro', 'Livro'), ('manga', 'Manga'), ('manhwa', 'Manhwa'), ('manhua', 'Manhua')], max_length=20)),
                ('autor', models.CharField(blank=True, max_length=255)),
                ('capa_url', models.URLField(blank=True)),
                ('site_base_url', models.URLField(blank=True, verbose_name='URL do site')),
                ('total_capitulos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de capítulos')),
                ('status_obra', models.CharField(choices=[('em_andamento', 'Em andamento'), ('completo', 'Completo'), ('hiato', 'Hiato'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20, verbose_name='Status da obra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generos', models.ManyToManyField(blank=True, to='core.genero', verbose_name='Gêneros')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.PositiveIntegerField(verbose_name='Capítulo')),
                ('pagina', models.PositiveIntegerField(default=1, verbose_name='Página')),
                ('url_acessada', models.URLField(blank=True, verbose_name='URL acessada')),
                ('lido_em', models.DateTimeField(auto_now_add=True, verbose_name='Lido em')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.obra')),
            ],
            options={
                'verbose_name': 'Histórico de Leitura',
                'verbose_name_plural': 'Histórico de Leituras',
                'ordering': ['-lido_em'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo_atual', models.PositiveIntegerField(default=1, verbose_name='Capítulo atual')),
                ('pagina_atual', models.PositiveIntegerField(default=1, verbose_name='Página atual')),
                ('url_atual', models.URLField(blank=True, verbose_name='URL atual')),
                ('status_leitura', models.CharField(choices=[('lendo', 'Lendo'), ('pausado', 'Pausado'), ('completo', 'Completo'), ('abandonado', 'Abandonado')], default='lendo', max_length=20, verbose_name='Status de leitura')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('ultimo_acesso', models.DateTimeField(auto_now=True, verbose_name='Último acesso')),
                ('obra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='core.obra')),
            ],
            options={
                'verbose_name': 'Progresso de Leitura',
                'verbose_name_plural': 'Progressos de Leitura',
            },
        ),
    ]
