# Generated by Django 6.0.3 on 2026-04-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Imagem da capa'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='capa_url',
            field=models.URLField(blank=True, verbose_name='URL da capa (alternativa)'),
        ),
    ]
