# Generated by Django 6.0.3 on 2026-04-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_obra_capa_alter_obra_capa_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='obra',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas pessoais'),
        ),
    ]
