# Generated by Django 6.0.3 on 2026-04-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_obra_descricao_obra_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='classificacao',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], null=True, verbose_name='Classificação'),
        ),
    ]
