# Generated by Django 5.2.13 on 2026-04-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_favorito_alter_genero_id_alter_historicoleitura_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='favorito',
            field=models.BooleanField(default=False, verbose_name='Favorito'),
        ),
    ]
